version: 2
jobs:
  build:
    working_directory: ~/high_water_mark
    docker:
      - image: apiology/circleci-ruby:latest
    steps:
      - checkout
      - type: cache-restore
        key: high_water_mark-{{ checksum "high_water_mark.gemspec" }}-{{ checksum "Gemfile" }}
      - run: gem install bundler
      - run: bundle install --path vendor/bundle --jobs=4
      - type: cache-save
        key: high_water_mark-{{ checksum "high_water_mark.gemspec" }}-{{ checksum "Gemfile" }}
        paths:
          - "vendor/bundle"
      - run: bundle exec rake --jobs=4 ci
